import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { execFileSync } from "node:child_process";
import { readFile } from "node:fs/promises";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/
`;

const prod = process.argv[2] === "production";

function git(...args) {
	return execFileSync("git", args, { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
}

/** Build identity for `src/shared/build-info.ts`; a dev build without git degrades to `{ dev: true }`. */
function buildInfo() {
	if (prod) return { dev: false };
	try {
		return {
			dev: true,
			sha: git("rev-parse", "--short", "HEAD"),
			branch: git("rev-parse", "--abbrev-ref", "HEAD"),
			dirty: git("status", "--porcelain").length > 0,
			builtAt: new Date().toISOString(),
		};
	} catch {
		return { dev: true };
	}
}

// `define` is fixed at context creation, so the constant is injected into the one
// module that declares it via onLoad, which re-runs on every watch rebuild.
const buildInfoPlugin = {
	name: "synapse-build-info",
	setup(build) {
		build.onLoad({ filter: /[\\/]src[\\/]shared[\\/]build-info\.ts$/ }, async (args) => {
			const source = await readFile(args.path, "utf8");
			const constant = JSON.stringify(JSON.stringify(buildInfo()));
			return { contents: `const __SYNAPSE_BUILD__ = ${constant};\n${source}`, loader: "ts" };
		});
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		// Keep Node builtins external in BOTH bare (`fs`) and `node:`-prefixed
		// (`node:fs`) forms so the loader's lazy requires resolve at runtime on
		// desktop and esbuild never tries to bundle them.
		...builtinModules,
		...builtinModules.map((m) => `node:${m}`),
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	// Inline `*.md` imports as strings so CHANGELOG.md ships in the bundle and
	// can be rendered in the in-app changelog view (#375).
	loader: { ".md": "text" },
	plugins: [buildInfoPlugin],
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
