/** Topic extracted from a note's content via AI analysis. */
export interface ExtractedTopic {
	/** Note-title-worthy name */
	title: string;
	/** One-sentence scope description */
	description: string;
	/** Relevance confidence (0-1) */
	relevance: number;
	/** Whether a vault note with this title already exists */
	existsInVault: boolean;
	/** Path of the existing note, if any */
	existingPath?: string;
	/** URLs from the source note related to this topic */
	relatedUrls: string[];
}

/** Local heuristic score to decide whether to recurse deeper. */
export interface QualityScore {
	/** Overall score (0-1); below threshold stops recursion */
	score: number;
	/** Number of child topics extracted */
	topicCount: number;
	/** Word count of the generated content */
	wordCount: number;
	/** True if the title is too generic (1-word or common term) */
	isTooGeneric: boolean;
	/** True if most child topics overlap with ancestors */
	hasHighOverlap: boolean;
	/** Human-readable explanation of the score */
	reasoning: string;
}

/** Status of a deep dive proposal. */
export type DeepDiveProposalStatus = 'pending' | 'accepted' | 'rejected';

/** A single proposed child note generated by deep dive. */
export interface DeepDiveProposal {
	id: string;
	/** ID of the DeepDiveRun this belongs to */
	runId: string;
	/** Path of the note this was extracted from */
	sourceNotePath: string;
	/** The topic that was extracted */
	topic: ExtractedTopic;
	/** Where the new note would be created */
	proposedPath: string;
	/** Full markdown content for the new note */
	proposedContent: string;
	/** Depth in the tree (0 = direct child of root) */
	depth: number;
	/** Quality score from local heuristic */
	qualityScore: QualityScore;
	/** IDs of proposals generated from this note */
	childProposalIds: string[];
	createdAt: string;
	status: DeepDiveProposalStatus;
}

/** Status of a deep dive run. */
export type DeepDiveRunStatus = 'in-progress' | 'completed' | 'cancelled';

/** Metadata for one invocation of the deep dive command. */
export interface DeepDiveRun {
	id: string;
	/** Root note that started the dive */
	rootNotePath: string;
	/** Max depth configured for this run */
	maxDepth: number;
	/** Quality threshold configured for this run */
	qualityThreshold: number;
	/** All proposal IDs in this run */
	proposalIds: string[];
	stats: {
		totalProposals: number;
		byDepth: Record<number, number>;
		earlyTerminations: number;
	};
	createdAt: string;
	status: DeepDiveRunStatus;
}
